name: Install μpkg
description: Install μpkg
inputs:
  version:
    description: The version of μpkg to install
    default: latest
    required: false
  install-prefix:
    description: Where to install μpkg
    default: ""
    required: false
  install-dependencies:
    description: Whether to install dependencies in the current working-directory
    default: 'true'
    required: false
  working-directory:
    description: "The working directory to change to before installing dependencies"
    default: "."
    required: false
outputs:
  version:
    description: The μpkg version that was installed
    value: ${{ steps.install.outputs.version }}
  install-prefix:
    description: Where μpkg was installed
    value: ${{ steps.install.outputs.install-prefix }}
runs:
  using: composite
  steps:
  - name: Install μpkg
    id: install
    shell: bash
    run: |
      if [[ -z $INSTALL_PREFIX ]]; then
        INSTALL_PREFIX=$HOME/.local
        [[ $EUID != 0 ]] || INSTALL_PREFIX=/usr/local
      fi
      wget -qO- https://github.com/orbit-online/upkg/releases/${{ inputs.version != 'latest' && 'download/' || '' }}${{ inputs.version }}/${{ inputs.version == 'latest' && 'download/' || '' }}upkg-install.tar.gz | \
        tar -xzC "$INSTALL_PREFIX"
      printf "install-prefix=%s\n" "$INSTALL_PREFIX" >> $GITHUB_OUTPUT
      VERSION=$($INSTALL_PREFIX/bin/upkg list -g -- -J | jq -r '.packages[] | select(.name=="upkg") | .version')
      printf "version=%s\n" "$VERSION" >> $GITHUB_OUTPUT
    env:
      INSTALL_PREFIX: ${{ inputs.install-prefix }}
  - name: Install dependencies
    shell: bash
    run: ${{ steps.install.outputs.install-prefix }}/bin/upkg install
    working-directory: ${{ inputs.working-directory }}
    if: ${{ inputs.install-dependencies == 'true' }}
